In [5]:
#1. Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [4]:
#2. Load the dataset
df = pd.read_csv("../data/student-mat.csv", sep=";")

df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5,4,6,10,10

In [3]:
#3. Check dataset dimensions
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 395
Number of columns: 33

In [6]:
#4. Understand all columns
df.columns.tolist()

['school',
 'sex',
 'age',
 'address',
 'famsize',
 'Pstatus',
 'Medu',
 'Fedu',
 'Mjob',
 'Fjob',
 'reason',
 'guardian',
 'traveltime',
 'studytime',
 'failures',
 'schoolsup',
 'famsup',
 'paid',
 'activities',
 'nursery',
 'higher',
 'internet',
 'romantic',
 'famrel',
 'freetime',
 'goout',
 'Dalc',
 'Walc',
 'health',
 'absences',
 'G1',
 'G2',
 'G3']

In [7]:
#5. Check data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [8]:
#6. Check missing values
missing = df.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

In [9]:
#7. Check duplicate records
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [10]:
#8. Separate numerical and categorical columns
numerical_cols = df.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_cols = df.select_dtypes(
    include=["object"]
).columns

print("Numerical columns:")
print(numerical_cols.tolist())

print("\nCategorical columns:")
print(categorical_cols.tolist())

Numerical columns:
['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

Categorical columns:
['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']

In [11]:
#9. Check unique values
for col in categorical_cols:
    print(f"\n{col}:")
    print(df[col].unique())

school:
['GP' 'MS']

sex:
['F' 'M']

address:
['U' 'R']

famsize:
['GT3' 'LE3']

Pstatus:
['A' 'T']

Mjob:
['at_home' 'health' 'other' 'services' 'teacher']

Fjob:
['teacher' 'other' 'services' 'health' 'at_home']

reason:
['course' 'other' 'home' 'reputation']

guardian:
['mother' 'father' 'other']

schoolsup:
['yes' 'no']

famsup:
['no' 'yes']

paid:
['no' 'yes']

activities:
['no' 'yes']

nursery:
['yes' 'no']

higher:
['yes' 'no']

internet:
['no' 'yes']

romantic:
['no' 'yes']

In [12]:
#10. Check numerical distributions
df[numerical_cols].describe().T

            count       mean       std   min   25%   50%   75%   max
age         395.0  16.696203  1.276043  15.0  16.0  17.0  18.0  22.0
Medu        395.0   2.749367  1.094735   0.0   2.0   3.0   4.0   4.0
Fedu        395.0   2.521519  1.088201   0.0   2.0   2.0   3.0   4.0
traveltime  395.0   1.448101  0.697505   1.0   1.0   1.0   2.0   4.0
studytime   395.0   2.035443  0.839240   1.0   1.0   2.0   2.0   4.0
failures    395.0   0.334177  0.743651   0.0   0.0   0.0   0.0   3.0
famrel      395.0   3.944304  0.896659   1.0   4.0   4.0   5.0   5.0
freetime    395.0   3.235443  0.998862   1.0   3.0   3.0   4.0   5.0
goout       395.0   3.108861  1.113278   1.0   2.0   3.0   4.0   5.0
Dalc        395.0   1.481013  0.890741   1.0   1.0   1.0   2.0   5.0
Walc        395.0   2.291139  1.287897   1.0   1.0   2.0   3.0   5.0
health      395.0   3.554430  1.390303   1.0   3.0   4.0   5.0   5.0
absences    395.0   5.708861  8.003096   0.0   0.0   4.0   8.0  75.0
G1          395.0  10.908861  3.319195   3.0   8.0  11.0  13.0  19.0
G2          395.0  10.713924  3.761505   0.0   9.0  11.0  13.0  19.0
G3          395.0  10.415190  4.581443   0.0   8.0  11.0  14.0  20.0

In [14]:
#11. Check our target variable
print(df["G3"].value_counts().sort_index())

G3
0     38
4      1
5      7
6     15
7      9
8     32
9     28
10    56
11    47
12    31
13    31
14    27
15    33
16    16
17     6
18    12
19     5
20     1
Name: count, dtype: int64

In [15]:
print("Average final grade:", df["G3"].mean())
print("Median final grade:", df["G3"].median())
print("Minimum:", df["G3"].min())
print("Maximum:", df["G3"].max())

Average final grade: 10.415189873417722
Median final grade: 11.0
Minimum: 0
Maximum: 20

In [16]:
#12. Create a performance category
def performance_category(score):
    if score < 10:
        return "Fail"
    elif score < 14:
        return "Average"
    elif score < 17:
        return "Good"
    else:
        return "Excellent"

df["performance_category"] = df["G3"].apply(performance_category)

In [17]:
df["performance_category"].value_counts()

performance_category
Average      165
Fail         130
Good          76
Excellent     24
Name: count, dtype: int64

In [18]:
#13. Create a pass/fail column
df["pass"] = np.where(df["G3"] >= 10, "Pass", "Fail")

In [19]:
df["pass"].value_counts()

pass
Pass    265
Fail    130
Name: count, dtype: int64

In [20]:
pass_rate = (df["pass"] == "Pass").mean() * 100
fail_rate = (df["pass"] == "Fail").mean() * 100

print(f"Pass Rate: {pass_rate:.2f}%")
print(f"Fail Rate: {fail_rate:.2f}%")

Pass Rate: 67.09%
Fail Rate: 32.91%

In [21]:
#14. Check for impossible values

In [22]:
# -> Age
print(df["age"].min())
print(df["age"].max())

15
22

In [23]:
# -> Absences
print(df["absences"].min())
print(df["absences"].max())

0
75

In [24]:
# -> Grades
print(df[["G1", "G2", "G3"]].min())
print(df[["G1", "G2", "G3"]].max())

G1    3
G2    0
G3    0
dtype: int64
G1    19
G2    19
G3    20
dtype: int64

In [25]:
#15. Save the cleaned dataset
df.to_csv(
    "../data/student_performance_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!